### ISSUE TITLE
logging 통합 필요

### ISSUE THREAD

**Issue by lightjune** [lightjune/jenkins-trigger#5]
지금 flask 자체에서 찍고 있는 로그는 어느 로그인지 모르겠다.
내부에서 exception 이 발생하거나, HTTP 요청, 응답에 대해서 계속 콘솔로 찍고 있다.
이게 존재하는데, 굳이 로그를 따로 만들 필요가 없는 것 같다.

이걸 통제할 방법을 찾아서 같은 포맷으로 같은데 찍도록 하자.

**Comment by lightjune** [comment]
생각보다 다루기가 어려운 것 같다. 
일단 flask 를 실행시키면 로거 2개가 기본으로 돌아간다. 
flask 의 "flask.app" 로거와 werkzeug 의 "werkzeug" 로거.
```
127.0.0.1 - - [23/Oct/2018 22:57:02] "POST /jenkins-trigger HTTP/1.1" 400 -
```
이게 werkzeug 로거로 찍히는 거고,
```
[2018-10-23 22:57:04,558] ERROR in app: Exception on /jenkins-trigger [POST]
Traceback (most recent call last):
  File "C:\Users\June03\Anaconda3\envs\flask\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\June03\Anaconda3\envs\flask\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\June03\Anaconda3\envs\flask\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\June03\Anaconda3\envs\flask\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\June03\Anaconda3\envs\flask\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\June03\Anaconda3\envs\flask\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\project\jenkins-trigger\main.py", line 26, in jenkins_trigger
    trigger.send_request(event.get_repository_name())
AttributeError: 'NoneType' object has no attribute 'get_repository_name'
```
이게 flask 로거로 찍히는 것이다.

직접 이름으로 호출해서 설정을 할 수는 있는데, werkzeug 로거같은 경우는 메시지 자체가 하드코딩되어 있어서 내가 원하는 포맷으로 고칠수가 없다.

- werkzeug/serving.py
``` python
def log(self, type, message, *args):
    _log(type, '%s - - [%s] %s\n' % (self.address_string(),
                                     self.log_date_time_string(),
                                     message % args))
```

**Comment by lightjune** [comment]
기존의 로거는 없애고 로깅이 필요할 때는 플라스크 디폴트 로거를 사용하자. werkzeug 는 그냥 분리해서 찍기로 하였다. 다른 내용이 있는 것도 아닌 것 같아서 분리해도 별로 의미는 없지만, 포맷이 통일이 안되어서 거슬린다. 결과적으로 네 개가 찍힐 것이다.
- ```flask.log```: 플라스크 기본 로깅(예외 스택) + 직접 메시지 넘겨서 찍는 로깅.
- ```werkzeug.log```: werkzeug 가 자체로 찍는 로깅.
- ```payload.log```: HTTP에 실려오는 것 보기 좋게 따로 로깅.
- ```uwsgi.log```: uwsgi 에서 찍는 로깅.
